#!/usr/bin/env bash
# fix_navigator_mac.sh -- macOS + Anaconda Navigator only.
#
# Run this ONCE, right after `conda env create -f environment.yml`, so that
# Anaconda Navigator's "Notebook" Launch button works for the atoc4815
# environment.
#
# Why this is needed: environment.yml installs everything from the
# conda-forge channel (deliberately -- it has the best/most current builds
# of cartopy, pyhdf, etc. for Apple Silicon Macs). conda-forge's build of
# `notebook` does not ship the little launcher script
# (<env>/bin/jupyter_mac.command) that Anaconda Navigator looks for before
# it will show a "Launch" button -- that script is normally generated by
# Anaconda's own `defaults`-channel build instead. `notebook` itself is
# correctly installed and fully functional either way; Navigator's GUI
# button is just looking for a file that this build never creates. This
# script creates that one small file so the button works.
#
# Usage:
#   bash fix_navigator_mac.sh
#
set -e

ENV_NAME="atoc4815"
ENV_PREFIX="$(conda env list | awk -v e="$ENV_NAME" '$1==e {print $NF}')"

if [ -z "$ENV_PREFIX" ]; then
    echo "Could not find the '$ENV_NAME' environment."
    echo "Create it first with:  conda env create -f environment.yml"
    exit 1
fi

BIN="$ENV_PREFIX/bin"
LAUNCHER="$BIN/jupyter_mac.command"

cat > "$LAUNCHER" << 'LAUNCHEREOF'
#!/usr/bin/env bash
# Auto-generated so Anaconda Navigator can start Jupyter Notebook for this
# environment. Just runs the jupyter-notebook binary that lives right next
# to this script, whatever machine/location the environment is installed in.
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$HOME"
exec "$DIR/jupyter-notebook"
LAUNCHEREOF

chmod +x "$LAUNCHER"

echo "Done. Anaconda Navigator's Notebook button should now work for '$ENV_NAME'."
echo "(If Navigator is already open, quit and reopen it -- or click the refresh"
echo " icon next to the environment dropdown -- so it notices the new file.)"
